### ISSUE TITLE
Fix code scanning alert - Use of a broken or weak cryptographic hashing algorithm on sensitive data

### ISSUE THREAD

**Issue by meysam81** [licenseware/licenseware-sdk-v2#277]
Tracking issue for:
- [ ] https://github.com/licenseware/licenseware-sdk-v2/security/code-scanning/6

**Comment by ClimenteA** [comment]
The file can be deleted + it's a false positive. The analyzer doesn't detect the context.  There are more going on there..
These crappy analyzers just waste electricity in 90% of the cases :))
